/* eslint-disable */
const english = {
  text1: "The user does not exist",
  text2: "User is deactivated",
  text3: "Please configure your PIN",
  text4: "Welcome to LamedCash",
  text5: "To get started, please log in to your account or create a new one.",
  text6: "Register",
  text7: "Login",
  text8: `By pressing "Create an account" or "Login", you accept our terms.`,
  text9: "incorrect password",
  text10: "Enter the correct details",
  text11: "Sign in",
  text12: "Sign into your account",
  text13: "* Please enter a valid mail",
  text14: "* Password is too short",
  text15: "Forgot your password?",
  text16: "Continue",
  text17: "You do not have an account?",
  text18: "register here",
  text19: "Sorry Only Beninese numbers are allowed",
  text20: "user already exists",
  text21: "Failed to create your data",
  text22: "The referrer does not exist",
  text23: "Register",
  text24: "Get Started",
  text25: "Create an account to get started",
  text26: "Please enter a valid name",
  text27: "First and last name",
  text28: "Please enter a valid mail",
  text29: "Please enter a valid Id",
  text30: "Id too short",
  text31: "Id must be numbers",
  text32: "Too short and not numbers",
  text33: "Id 1xbet",
  text34: "Please enter a valid phone number",
  text35: "Phone number",
  text36: "Password is too short ",
  text37: "Password",
  text38: "Does not match password field",
  text39: "Confirm the password",
  text40: "Reference (optional)",
  text41:
    "Don't worry, it happens. Please enter your email address associated with your account.",
  text42: "You remember your contact details",
  text43: "ID copied successfully",
  text44: "Hello",
  text45: "Recharge",
  text46: "Withdraw",
  text47: "Amount",
  text48: "Connected successfully",
  text49: "pending",
  text50: "Recent Activities",
  text51: "See more",
  text52: "You have no recent transactions",
  text53: "RECHARGE",
  text54: "WITHDRAW",
  text55: "BONUS",
  text56: "SEND",
  text57: "RECEIVE",
  text58: "Failed",
  text59: "Successful",
  text60: "Pending",
  text61: "Transaction History",
  text62: "Completed",
  text63: "All",
  text64: "Cancelled",
  text65: "Details",
  text66: "initialize",
  text67: "Completed",
  text68: "Amount payed",
  text69: "Bonus used",
  text70: "Failed",
  text71: "Failed to use for Recharge.",
  text72: "Awaiting Approval",
  text73: "Approval",
  text74: "Transaction details",
  text75: "Payment method",
  text76: "For Recharge",
  text77: "payment confirmation",
  text78: "ID",
  text79: "Number",
  text80: "Transaction date",
  text81: "Transaction ID",
  text82:
    "The transaction wasn't completed because the POS currency does not match the customer's account currency.",
  text83:
    "The transaction wasn't completed because Your Payment wasn't accepted",
  text84: "The transaction wasn't completed because a payment of",
  text85: "has already been made to customer",
  text86:
    "has already been made to customer #${specificData.id}. This payment can be made again in 5 minutes",
  text87: "Account",
  text88: "We reward you for using our services",
  text89: "",
  text90: "Send to a friend",
  text91: "View history",
  text92: "Wallet History",
  text93: "SENT",
  text94: "CREDITED",
  text95: "Used for Recharge",
  text96: "Sent to",
  text97: "Received from",
  text98: "Added to wallet",
  text99: "Used for withdrawal",
  text100: "Personal Information",
  text101: "Edit your information",
  text102: "My Referral",
  text103: "Referrals",
  text104: "Settings",
  text105: "Account, notification",
  text106: "Light mode",
  text107: "Switch app display mode to your preference",
  text108: "Support",
  text109: "Help or contact us",
  text110: "Legal",
  text111: "Help, Privacy & Security, Legal",
  text112: "Sign Out",
  text113: "Sign out of your account",
  text114: "upload photo",
  text115:
    "Your LamedCash profile is your personal gateway to manage your Account Information.",
  text116: "Profile",
  text117: "Dark mode",
  text118: "Edit Profile",
  text119: "Edit LamedCash Profile",
  text120: "Set Tag",
  text121: "Change Tag",
  text122: "Name",
  text123: "Please enter a valid phone number",
  text124: "Update",
  text125: "Your information has been successfully updated",
  text126: "Failed to update information",
  text127: "Invalid number",
  text128: "Change your default tag.",
  text129: "Label",
  text130: "Account Security",
  text131: "Reset password, Reset pin.",
  text132: "Push, Email Notification.",
  text133: "Reset password",
  text134: "Update your password",
  text135: "Reset LamedCash PIN",
  text136: "Update your security PIN",
  text137: "Security",
  text138: "new password and password confirmation do not match",
  text139: "Password was successfully updated",
  text140: "Change Password",
  text141: "New password",
  text142: "The PIN code has expired.",
  text143: "Invalid PIN or user ID.",
  text144: "Change pin",
  text145: "Request code",
  text146: "Your profile picture has been successfully updated",
  text147: "No images uploaded",
  text148: "User not found",
  text149: "Unable to download this month",
  text150: "How can we help you?",
  text151:
    "At LamedCash we are committed to providing you with the best possible experience. If you have any questions, concerns or issues, we are here to help.",
  text152: "Give Us A Call",
  text153: "Permission Required",
  text154:
    "This app needs camera permissions to work. Please grant the permission in settings.",
  text155: "Enter a new PIN.",
  text156: "unable to perform the operation",
  text157: "The pins are not the same",
  text158: "Pin set successfully",
  text159: "Privacy policy",
  text160: "Read more about our privacy policy",
  text161: "Terms and condition",
  text162: "Read more about our terms and condition",
  text163: "english",
  text164: "Home",
  text165: "Community",
  text166: "Switch Language",
  text167: "Switch app display language to your preference",
  text168: "English",
  text169: "French",
  text170: "Overview",
  text171: "Lineups",
  text172: "Stats",
  text173: "Substitution",
  text174: "Red Card",
  text175: "Yellow Card",
  text176: "Corner",
  text177: "Goal",
  text178: "Own-goal",
  text179: "Penalty",
  text180: "Penalty Missed",
  text181: "Details",
  text182:
    "Rewards from your transactions and referral transations are added here and you can use them to make top-ups, withdraw them or send to friends and family",
  text183: "Rules",
  text184: "History",
  text185: "Rewards Rules",
  text186:
    "Get wallet bonus by referring your friends to the app or completing tasks such as: deposits and withdrawals to your bet account and other activities on the app. Wallet Bonus will be issued automatically to your account and can be used to make payments for deposits and withdrawals, sent to friends and perform other activities.",
  text187: "1. Benefits of the Wallet Bonus Promotion",
  text188:
    "The wallet bonus is limited to only users who meet the following criteria;",
  text189: "1. Install the latest version of the LamedCash App.",
  text190: "2. Register, perform activities and refer friends.",
  text191: "2. Who qualifies for the Welcome Bonus?",
  text192:
    "You will receive your wallet bonus as soon as the system verifies you completing the required tasks. Bonus would be sen only after it is verified",
  text193: "3. Task breakdown",
  text194: "AMOUNT",
  text195: "NUMBER",
  text196: "Referral",
  text197: "General Settings",
  text198: "Request Top Up from a friend",
  text199: "Proceed",
  text200: "Currency must be in XOF.",
  text201: "Take note",
  text202: "Withdrawal code",
  text203: "Number",
  text204: "Confirm Number",
  text205: "Enter the amount",
  text206: "available for use",
  text207: "amount",
  text208: "Withdraw from your wallet balance",
  text209: "Recharge",
  text210: "This payment can be made again in 5 minutes.",
  text211: "Done",
  text212: "Withdrawal",
  text213: "amount",
  text214: "Failed to use for Withdrawal.",
  text215: "For withdrawal",
  text216: "Withdrawal Code",
  text217: "Upcoming",
  text218: "Live",
  text219: "Finished",
  text220: "Filter",
  text221: "AMOUNT",
  text222: "NUMBER",
  text223: "Configure your app PIN.",
  text224: "Welcome",
  text225: "Please enter the PIN again.",
  text226: "Almost done",
  text227: "Set pin",
  text228: "Your account currency must be in XOF.",
  text229: 'USE THIS PROMO CODE "229LERICHE"',
  // text229:
  //   'USE THIS PROMO CODE "229LERICHE" ON 1XBET AND GET 200% BONUS ON YOUR FIRST DEPOSIT',
  text230: "Got it",
  text231: "A payment of",
  text232: "Deduct from bonus",
  text233: "Your bonus funds would be added to the transaction.",
  text234: "Balance",
  text235: "Cancel",
  text236: "Edit Post",
  text237: "Edit",
  text238: "Comments",
  text239: "Following",
  text240: "Follow",
  text241: "Posts",
  text242: "Followers",
  text243: "Delete",
  text244: "Edit",
  text245: "commented on your post",
  text246: "Likes",
  text247: "Favourites",
  text248: "What's on your mind?",
  text249: "Create Post",
  text250: "Post",
  text251: "No posts for you at the moment",
  text252: "Added Post to Favorites",
  text253: "Removed Post from Favorites",
  text254: "No Comments yet",
  text255: "comment",
  text256: "View all",
  text257: "For You",
  text258: "Community",
  text259: "Write a reply...",
  text260: "You haven't saved any post yet!!!",
  text261: "No comments yet.",
  text262: "You haven't liked any post yet!!!",
  text263: "No views on this post yet!!!",
  text264: "See Posts",
  text265: "See more Data",
  text266: "You have no notification",
  text267: "Notification History",
  text268: "SEND TO A FRIEND",
  text269: "Enter an email or tag to search",
  text270: "Send To",
  text271: "Please enter a valid Amount",
  text272: "Payment sent",
  text273: "From you",
  text274: "Received by",
  text275: "Recipient details",
  text276: "From the bonus balance",
  text277: "you",
  text278: "Payment of",
  text279: "Received",
  text280: "Received from",
  text281: "Payment to",
  text282: "Share",
  text283: "Payment method",
  text284: "Added to your wallet balance",
  text285: "Credit wallet",
  text286: "Transaction date",
  text287:
    "A five-digit PIN has been sent to your email, enter it to reset your PIN",
  text288: "Follow",
  text289: "Following",
  text290: "You haven't made any comments yet!!!",
  text291: "Your Comment",
  text292: "Follow Someone to see their posts",
  // text293:
  //   "Refer Friends to LamedCash and Earn Rewards! Share Your Code And Get Bonuses When They Sign Up And Make Transactions. You Will Also Receive 33% of our profits On Your Referral Deposits. Start Sharing Your Unique Code Now!",
  text293:
    "Refer Friends to LamedCash and Earn Rewards! Start Sharing Your Unique Code Now!",
  text294: "Invite your friends and get 33% of our profits on your affiliates",
  text295: "Your unique referral code",
  text296: "Copy your code",
  text297: "Create a unique referral code",
  text298: "Create a unique referral code below",
  text299: "tag",
  text300: "Create",
  text301: "Refer a friend",
  text302: "See your unique referral code",
  text303: "Refer a friend",
  text304: "Successfully set id",
  text305: "The label is the same as the old one",
  text306: "The tag already exists",
  text307: "Sorry Only Beninese numbers are allowed",
  text308: "You haven't invited a friend yet",
  // text309:
  //   "Share your unique LamedCash code and get a 33% of our profits on all their deposits. Let's spread the word and win together",
  text309: "",
  text310: "I accept the conditions (NOT SUITABLE FOR UNDER 18)",
  text311: "Accept the terms and conditions to proceed",
  text312: "No biometric hardware available.",
  text313: "No biometrics are enrolled. Please set up Face ID or fingerprint.",
  text314: "Authenticate with Face ID or fingerprint",
  text315: "Use Passcode",
  text316: "Authentication successful!",
  text317: "Authentication failed. Please try again.",
  text318: "Authentication error:",
  text319: "An error occurred during authentication. Please try again.",
  text320: "SUCCESSFUL",
  text321: "FAILED",
  text322: "PENDING",
  text323: "RECEIVED",
  text324: "SENT",
  text325: "The Recharge of",
  text326: "The withdrawal of",
  text327: "The amount of",
  text328: "has been received from",
  text329: "The bonus of",
  text330: "has been received by you.",
  text331: "has been successfully sent to",
  text332: "is currently Pending.",
  text333: "was Rejected.",
  text334: "has been made Successfully.",
  text335: "is currently Pending.",
  text336: "has Failed.",
  text337: "Awaiting Confirmation. Please do not leave this page.",
  text338:
    "A five-digit PIN has been sent to your email, enter it to reset your password",
  text339: "Your referral code has been copied",
  text340: "Send us a message",
  text341: "Send us a tweet",
  text342: "Account Deletion",
  text343: "Delete your account",
  text344:
    "If you wish to proceed with deleting your account, fill the form and submit below",
  text345: "Submit my request",
  text346: "Delete My Account",
  text347:
    "Are you absoluely sure you want to delete your account data from LamedCash? We are really sorry to see you go 😟",
  text348: "Delete Confirmation",
  text349: "Cancel",
  text350: "Proceed",
  text351: "Input your email and Password",
  text352: "Currently under maintainance",
  text353: "Password is incorrect",
  text354:
    "Operation was successful, You would be sent a mail....when your request has been fulfilled usually within 2 weeks, You would be logged out now and your account deactivated",
  text355: "VILLE",
  text356: "STREET",
  text357: "VIEW ONLY LIVE SPORTS EVENTS!!",
  text358:
    "Use your rewards to top up account, make a withdrawal  or send to a friend",
  text359: "Make a Withdrawal",
  text360: "Top up account",
  text361: "Pending Top Ups",
  text362: "Pending Withdrawals",
  text363: "No QR Code generated yet, enter details to generate",
  text364: "Request Top Ups",
  text365: "Soccer tips",
  text366: "TIPSTER PICKS",
  text367: "TAP TO VIEW",
  text368: "2 SURE ODDS",
  text369: "HISTORY",
  text370: "TODAY",
  text371: "Make a deposit of any amount to access for today",
  text372: "No Games To Display Yet",
  text373: "Make A Deposit Today To See Games",
  text374: "Update And Delete",
  text375: "Create",
};

const french = {
  text1: "L'utilisateur n'existe pas",
  text2: "L'utilisateur est désactivé",
  text3: "Veuillez configurer votre code PIN",
  text4: "Bienvenue chez LamedCash",
  text5:
    "Pour commencer, veuillez vous connecter à votre compte ou en créer un nouveau.",
  text6: "S'inscrire",
  text7: "Connecter",
  text8: `En appuyant sur "Créer un compte" ou "Connexion", vous acceptez nos conditions.`,
  text9: "Mot de passe incorrect",
  text10: "Entrez les détails corrects",
  text11: "Se Connecter",
  text12: "Connectez-vous à votre compte",
  text13: "* Veuillez saisir un mail valide",
  text14: "* Le mot de passe est trop court",
  text15: "Mot de passe oublié?",
  text16: "Continuer",
  text17: "Vous n'avez pas de compte?",
  text18: "Inscrivez-vous ici",
  text19: "Désolé Seuls les numéros béninois sont autorisés",
  text20: "l'utilisateur existe déjà`",
  text21: "Échec de la création de vos données",
  text22: "Le référent n'existe pas",
  text23: "Registre",
  text24: "Commencer",
  text25: "Créez un compte pour commencer.",
  text26: "Merci d'entrer un nom valide",
  text27: "Nom et prénom",
  text28: "Veuillez entrer un email valide",
  text29: "Veuillez saisir un identifiant valide",
  text30: "Id trop court",
  text31: "L'identifiant doit être composé de chiffres",
  text32: "Trop court et pas Nombres",
  text33: "Id 1xbet",
  text34: "s'il vous plaît entrer un numéro de téléphone valide",
  text35: "Numéro de téléphone",
  text36: "Le mot de passe est trop court",
  text37: "Mot de passe",
  text38: "Ne correspond pas au champ du mot de passe",
  text39: "Confirmez le mot de passe",
  text40: "Référence (facultatif)",
  text41:
    "Ne vous inquiétez pas, cela arrive. Veuillez saisir votre adresse e-mail associée à votre compte.",
  text42: "Vous vous souvenez de vos coordonnées",
  text43: "ID copié avec succès",
  text44: "Bonjour",
  text45: "Recharge",
  text46: "Retirer",
  text47: "Montant",
  text48: "Connecté avec succès",
  text49: "en attente",
  text50: "Activités récentes",
  text51: "Voir plus",
  text52: "Vous n'avez aucune transaction récente",
  text53: "RECHARGE",
  text54: "RETRAIT",
  text55: "PRIME",
  text56: "ENVOYER",
  text57: "RECEVOIR",
  text58: "Échoué",
  text59: "Réussi",
  text60: "En attente",
  text61: "Historique des transactions",
  text62: "Complété",
  text63: "Tout",
  text64: "Annulé",
  text65: "Détails",
  text66: "initialise la",
  text67: "complétéd",
  text68: "montant payé",
  text69: "Bonus utilisé",
  text70: "Échoué",
  text71: "Impossible de l'utiliser pour la recharge.",
  text72: "En attente d'approbation",
  text73: "Approbation",
  text74: "Détails de la transaction",
  text75: "Mode de paiement",
  text76: "Pour Recharger",
  text77: "confirmation de paiement ",
  text78: "IDENTIFIANT",
  text79: "Nombre",
  text80: "Date de la transaction",
  text81: "Id de transaction",
  text82:
    "La transaction n'a pas été finalisée car la devise du point de vente ne correspond pas à la devise du compte du client.",
  text83:
    "La transaction n'a pas été complétée car votre paiement n'a pas été accepté",
  text84: "La transaction n'a pas été finalisée, car un paiement de",
  text85: "a déjà été effectué au client",
  text86: "Ce paiement peut être effectué à nouveau dans 5 minutes.",
  text87: "Compte",
  text88: "Nous vous récompensons pour l'utilisation de nos services",
  text89: "",
  text90: "Envoyer",
  text91: "Voir l'historique",
  text92: "Historique du portefeuille",
  text93: "ENVOYÉ",
  text94: "CRÉDITÉ",
  text95: "Utilisé pour recharger",
  text96: "Envoyé à",
  text97: "reçu de",
  text98: "Ajouté au portefeuille",
  text99: "Utilisé pour le retrait",
  text100: "Informations personnelles",
  text101: "Modifiez vos informations",
  text102: "Ma Référence",
  text103: "Références",
  text104: "Paramètres",
  text105: "Compte, notification",
  text106: "Mode lumière",
  text107: "Changez le mode d'affichage de l'application selon vos préférences",
  text108: "Support",
  text109: "Aidez-nous ou contactez-nous",
  text110: "Légale",
  text111: "Aide, Confidentialité et sécurité, Mentions légales",
  text112: "Se déconnecter",
  text113: "Déconnectez-vous de votre compte",
  text114: "Envoyer la photo",
  text115:
    "Votre profil LamedCash est votre passerelle personnelle pour gérer votre Information sur le compte.",
  text116: "Profil",
  text117: "Mode sombre",
  text118: "Editer le profil",
  text119: "Modifier le profil LamedCash",
  text120: "Définir la balise",
  text121: "Changer la balise",
  text122: "Nom",
  text123: "S'il vous plaît entrer un téléphone valide nombre",
  text124: "Mise à jour",
  text125: "Vos informations ont été mises à jour avec succès",
  text126: "Échec de la mise à jour des informations",
  text127: "Numéro invalide",
  text128: "Modifiez votre balise par défaut.",
  text129: "Étiqueter",
  text130: "Sécurité du compte",
  text131: "Réinitialiser le mot de passe, réinitialiser le code PIN.",
  text132: "Push, notification par e-mail.",
  text133: "Réinitialiser le mot de passe",
  text134: "Mettez à jour votre mot de passe",
  text135: "Réinitialiser le code PIN de LamedCash",
  text136: "Mettez à jour votre code PIN de sécurité.",
  text137: "Sécurité",
  text138:
    "le nouveau mot de passe et la confirmation du mot de passe ne correspondent pas",
  text139: "Le mot de passe a été mis à jour avec succès",
  text140: "Changer le mot de passe",
  text141: "Nouveau mot de passe",
  text142: "Le code PIN a expiré.",
  text143: "Code PIN ou identifiant utilisateur invalide.",
  text144: "Changer l'épingle",
  text145: "Code requis",
  text146: "Votre photo de profil a été mise à jour avec succès",
  text147: "Aucune image téléchargée",
  text148: "Utilisateur non trouvé",
  text149: "impossible de télécharger ce mois-ci",
  text150: "Comment pouvons-nous vous aider?",
  text151:
    " Chez LamedCash, nous nous engageons à vous offrir le meilleur expérience possible. Si vous avez des questions, des préoccupations ou problèmes, nous sommes là pour vous aider.",
  text152: "Appelez-nous",
  text153: "Autorisation requise",
  text154:
    "Cette application a besoin des autorisations de la caméra pour fonctionner. Veuillez accorder l'autorisation dans les paramètres.",
  text155: "Entrez un nouveau code PIN.",
  text156: "incapable d'effectuer l'opération",
  text157: "Les épingles ne sont pas les mêmes",
  text158: "Épingler l'ensemble avec succès",
  text159: "Politique de confidentialité",
  text160: "En savoir plus sur notre politique de confidentialité",
  text161: "Termes et conditions",
  text162: "En savoir plus sur nos conditions générales",
  text163: "french",
  text164: "Accueil",
  text165: "Communauté",
  text166: "Changer la langue",
  text167:
    "Changez la langue d'affichage de l'application selon vos préférences",
  text168: "Anglais",
  text169: "Français",
  text170: "Aperçu",
  text171: "Compositions",
  text172: "Statistiques",
  text173: "Substitution",
  text174: "Carte Rouge",
  text175: "Carte Jaune",
  text176: "Coin",
  text177: "Goal",
  text178: "propre but",
  text179: "peine",
  text180: "penalty manqué",
  text181: "Details",
  text182:
    "Les récompenses de vos transactions et transactions de parrainage sont ajoutées ici et vous pouvez les utiliser pour effectuer des recharges, les retirer ou les envoyer à vos amis et à votre famille",
  text183: "Règles",
  text184: "Histoire",
  text185: "Règles de récompenses",
  text186:
    "Obtenez un bonus de portefeuille en référant vos amis à l'application ou en complétant des tâches telles que : les dépôts et les retraits sur votre compte de pari et d'autres activités sur l'application. Bonus de portefeuille sera émis automatiquement sur votre compte et peut être utilisé pour effectuer des paiements pour les dépôts et les retraits, envoyés à des amis et effectuer d'autres activités.",
  text187: "1. Avantages de la promotion Bonus Wallet",
  text188:
    "Le bonus du portefeuille est limité aux seuls utilisateurs qui remplissent les conditions critères suivants : ",
  text189: "1. Installez la dernière version de Application LamedCash.",
  text190: "2. Inscrivez-vous, effectuez des activités et référez-vous amis.",
  text191: "2. Qui est admissible au bonus de bienvenue ?",
  text192:
    "Vous recevrez votre bonus de portefeuille dès que le système aura vérifié que vous avez terminé les tâches requises. Le bonus ne sera envoyé qu'après avoir été vérifié",
  text193: "3. Répartition des tâches",
  text194: "MONTANT",
  text195: "NUMÉRO",
  text196: "Référence",
  text197: "Réglages généraux",
  text198: "Demander une recharge à un ami",
  text199: "Procéder",
  text200: "La devise doit être en XOF.",
  text201: "Prendre Note",
  text202: "Code de retrait",
  text203: "Numéro",
  text204: "Confirmer le numéro",
  text205: "Entrer le montant",
  text206: "disponible à l'emploi",
  text207: "Montant",
  text208: "Retirer du solde de votre portefeuille",
  text209: "Dépôts",
  text210: "Ce paiement peut être effectué à nouveau dans 5 minutes.",
  text211: "Fait",
  text212: "Retrait",
  text213: "montant",
  text214: "Échec de l'utilisation pour Retrait.",
  text215: "Pour retrait",
  text216: "Code de retrait",
  text217: "Pré-match",
  text218: "Live",
  text219: "Fini",
  text220: "Filtrer",
  text221: "MONTANT",
  text222: "NUMÉRO",
  text223: "Configurez votre code PIN d'application.",
  text224: "Bienvenu",
  text225: "Veuillez saisir à nouveau le code PIN.",
  text226: "Presque fini",
  text227: "Définir la broche",
  text228: "La devise de votre compte doit être en XOF.",
  text229: 'UTILISEZ LE CODE PROMO 1XBET "229LERICHE" ',
  // text229:
  //   'UTILISEZ LE CODE PROMO 1XBET "229LERICHE" ET OBTENEZ  200%  DE BONUS SUR VOTRE 1ER DÉPÔT',
  text230: "J'ai compris",
  text231: "Un paiement de",
  text232: "Déduire du bonus",
  text233: "Les fonds de votre bonus seraient ajoutés à la transaction.",
  text234: "Équilibre",
  text235: "Annuler",
  text236: "Modifier le message",
  text237: "Modifier",
  text238: "Commentaires",
  text239: "Suivis",
  text240: "Suivre",
  text241: "Postes",
  text242: "Followers",
  text243: "Supprimer",
  text244: "Modifier",
  text245: "j'ai commenté ton message",
  text246: "Likes",
  text247: "Favoris",
  text248: "Qu'est-ce qui préoccupe votre esprit?",
  text249: "Créer",
  text250: "Post",
  text251: "Aucune publication pour vous pour le moment",
  text252: "Publication ajoutée aux favoris",
  text253: "Message supprimé des favoris",
  text254: "Sans commentaires",
  text255: "commentaire",
  text256: "Voir tout",
  text257: "Suivi",
  text258: "Communauté",
  text259: "Écrire une réponse...",
  text260: "Vous n'avez encore enregistré aucun message !!!",
  text261: "Aucun commentaire pour l'instant.",
  text262: "Vous n'avez encore aimé aucun article!!!",
  text263: "Pas encore de vues sur ce post !!!",
  text264: "Voir le poste",
  text265: "Voir plus de données",
  text266: "Vous n'avez aucune notification",
  text267: "Historique des notifications",
  text268: "ENVOYER À UN AMI",
  text269: "Entrez un e-mail ou un tag pour rechercher",
  text270: "Envoyer à",
  text271: "Veuillez saisir un montant valide",
  text272: "Paiement envoyé",
  text273: "De toi",
  text274: "Reçu par",
  text275: "Détails du destinataire",
  text276: "Du solde bonus",
  text277: "toi",
  text278: "Paiement de",
  text279: "reçu",
  text280: "reçu du",
  text281: "Paiement à",
  text282: "Partager",
  text283: "Mode de paiement",
  text284: "Ajouté au solde de votre portefeuille",
  text285: "Crédit wallet",
  text286: "Date de la transaction",
  text287:
    "Un code PIN à cinq chiffres a été envoyé à votre adresse e-mail, saisissez-le pour réinitialiser votre code PIN",
  text288: "suivre",
  text289: "Invitez",
  text290: "Vous n'avez pas encore fait de commentaires !!!",
  text291: "Votre commentaire",
  text292: "Suivez quelqu'un pour voir ses publications",
  // text293:
  //   "Parrainez des amis sur LamedCash et gagnez des récompenses! Partagez votre code et obtenez des bonus lorsqu'ils s'inscrivent et effectuent des transactions. Vous recevrez également 33% de nos bénéfices sur vos dépôts de parrainage. Commencez à partager votre code unique maintenant!",
  text293:
    "Parrainez des amis sur LamedCash et gagnez des récompenses ! Commencez à partager votre code unique dès maintenant !",

  text294: "Invitez vous amis et obtenez 33% de nos profit sur vos affiliés",
  text295: "Votre code de parrainage unique",
  text296: "Copiez votre code",
  text297: "Créer un code de parrainage unique",
  text298: "Créez un code de parrainage unique ci-dessous",
  text299: "Étiqueter",
  text300: "Créer",
  text301: "Invitez un ami",
  text302: "Voir votre code de parrainage unique",
  text303: "Invitez un ami",
  text304: "Définir avec succès l'identifiant",
  text305: "L'étiquette est la même que l'ancienne",
  text306: "La balise existe déjà",
  text307: "Désolé Seuls les numéros béninois sont autorisés",
  text308: "Vous n'avez pas encore invité d'ami",
  // text309:
  //   "Partagez votre code LamedCash unique et obtenez 33% de nos bénéfices sur tous vos dépôts. Faisons passer le message et gagnons ensemble",
  text309: "",
  text310: "J'accepte les conditions (NE convient PAS AUX MOINS DE 18 ANS)",
  text311: "Acceptez les termes et conditions pour continuer",
  text312: "Aucun matériel biométrique disponible.",
  text313:
    "Aucune donnée biométrique n'est enregistrée. Veuillez configurer Face ID ou empreinte digitale.",
  text314: "Authentifiez-vous avec Face ID ou empreinte digitale",
  text315: "Utiliser le code d'accès",
  text316: "Authentification réussie !",
  text317: "Authentification échouée. Veuillez réessayer.",
  text318: "Erreur d'authentification:",
  text319:
    "Une erreur s'est produite lors de l'authentification. Veuillez réessayer.",
  text320: "RÉUSSI",
  text321: "ÉCHOUÉ",
  text322: "EN ATTENTE",
  text323: "REÇU",
  text324: "ENVOYÉ",
  text325: "La recharge de",
  text326: "Le retrait de",
  text327: "La quantité de",
  text328: "a été reçu de",
  text329: "La prime de",
  text330: "a été reçu par vous.",
  text331: "a été envoyé avec succès à",
  text332: "est actuellement en attente.",
  text333: "a été rejeté.",
  text334: "a été réalisé avec succès.",
  text335: "est actuellement en attente.",
  text336: "a échoué.",
  text337:
    "En attente de confirmation. S'il vous plaît ne quittez pas cette page.",
  text338:
    "Un code PIN à cinq chiffres a été envoyé à votre adresse e-mail, saisissez-le pour réinitialiser votre code Password",
  text339: "Votre code de parrainage a été copié",
  text340: "Envoyez-nous un message",
  text341: "Envoyez-nous un tweet",
  text342: "Suppression de compte",
  text343: "Supprimer votre compte",
  text344:
    "Si vous souhaitez procéder à la suppression de votre compte, remplissez le formulaire ci-dessous et soumettez-le",
  text345: "Soumettre ma demande",
  text346: "Supprimer mon compte",
  text347:
    "Etes-vous absolument sûr de vouloir supprimer les données de votre compte LamedCash ? Nous sommes vraiment désolés de vous voir partir 😟",
  text348: "Confirmation de suppression",
  text349: "Annuler",
  text350: "Procéder",
  text351: "Entrez votre email et votre mot de passe",
  text352: "Actuellement en maintenance",
  text353: "Le mot de passe est incorrect",
  text354:
    "L'opération a réussi, vous recevrez un e-mail... lorsque votre demande aura été satisfaite, généralement dans les 2 semaines, vous serez déconnecté maintenant et votre compte désactivé",
  text355: "CITY",
  text356: "RUE",
  text357: "VOIR UNIQUEMENT LES ÉVÉNEMENTS SPORTIFS EN DIRECT !!",
  text358:
    "Utilisez vos récompenses pour recharger votre compte, effectuer un retrait ou envoyer à un ami",
  text359: "Effectuer un Retrait",
  text360: "Recharger le compte",
  text361: "Recharger en attente",
  text362: "Retrait en attente",
  text363:
    " Aucun QR Code généré pour l'instant, entrez les détails pour générer",
  text364: "Demande de Recharges",
  text365: "Soccer tips",
  text366: "CÔTE DE 2",
  text367: "APPUYEZ POUR VOIR",
  text368: "CÔTE BONUS",
  text369: "HISTOIRE",
  text370: "TODAY",
  text371:
    "Effectuez un dépôt de n'importe quel montant pour y accéder dès aujourd'hui",
  text372: "Aucun jeu à afficher pour le moment",
  text373: "Faites un dépôt aujourd'hui pour voir les jeux",
  text374: "Update And Delete",
  text375: "Créer",
};

const Languages: any = { english, french };
const Language: any = { english, french };

export { Languages as default, Language };
