import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "../components/Nav";
import { TbArrowBigDownLinesFilled } from "react-icons/tb";
const inter = Inter({ subsets: ["latin"] });
import Head from "next/head";
export const metadata: Metadata = {
  title: "Espece",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, viewport-fit=cover"
        />
      </Head>
      <body className={inter.className}>
        <Nav />
        {children}
        <section className="hero-down-arrow">
          <TbArrowBigDownLinesFilled className="scroll-down-logo" />
        </section>
      </body>
    </html>
  );
}
